/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    tags: Tag;
    services: Service;
    projects: Project;
    brands: Brand;
    partners: Partner;
    'contact-submissions': ContactSubmission;
    clients: Client;
    proposals: Proposal;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    proposals: ProposalsSelect<false> | ProposalsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'rate-card-settings': RateCardSetting;
    'email-settings': EmailSetting;
  };
  globalsSelect: {
    'rate-card-settings': RateCardSettingsSelect<false> | RateCardSettingsSelect<true>;
    'email-settings': EmailSettingsSelect<false> | EmailSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Top-level groupings for services (Design, Development, etc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Auto-generated from title if left blank.
   */
  slug: string;
  /**
   * Shown under the category heading on /services.
   */
  blurb?: string | null;
  /**
   * Font Awesome icon name (e.g. "code", "palette", "pen-ruler"). Rendered as fa-slab fa-regular fa-{name}. Browse at https://fontawesome.com/icons?s=slab&m=regular
   */
  icon: string;
  displayOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable keywords/tools shown as chips on services.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Display form, e.g. "Astro", "E-commerce".
   */
  label: string;
  /**
   * Auto-generated from label if left blank.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  /**
   * Top-level grouping. Controls which section this appears in on /services.
   */
  category: number | Category;
  /**
   * Feature this service as a large card at the top of its category. Flagships sort above the rest; within flagships, lower displayOrder wins.
   */
  flagship?: boolean | null;
  /**
   * Font Awesome icon name (e.g. "code", "palette", "pen-ruler"). Rendered as fa-slab fa-regular fa-{name}. Leave blank to inherit the category icon. Browse at https://fontawesome.com/icons?s=slab&m=regular
   */
  icon?: string | null;
  /**
   * Reusable keywords/tools shown as chips (e.g. Astro, Payload, E-commerce).
   */
  tags?: (number | Tag)[] | null;
  /**
   * Short blurb for cards.
   */
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * One row per price variant. A flat-priced service needs a single row with just `amount`.
   */
  prices?:
    | {
        /**
         * e.g. "Single side", "8 pages", "5ft x 5ft". Omit for flat.
         */
        label?: string | null;
        amount: number;
        /**
         * e.g. "per month", "per page", "per word".
         */
        suffix?: string | null;
        /**
         * e.g. "invoiced based on usage", "starting from".
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  inclusions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  exclusions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  displayOrder?: number | null;
  /**
   * Not rendered publicly.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  /**
   * Short blurb for cards.
   */
  summary?: string | null;
  /**
   * Live URL.
   */
  url?: string | null;
  /**
   * Source repo URL, if public.
   */
  repoUrl?: string | null;
  /**
   * Client name, or blank for internal/personal.
   */
  client?: string | null;
  /**
   * Cover image for listings.
   */
  cover?: (number | null) | Media;
  /**
   * Free-form tags - mix of tech and domain (e.g. "astro", "shopify", "pwa", "visualization").
   */
  tags?: string[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featured?: boolean | null;
  displayOrder?: number | null;
  /**
   * Not rendered publicly.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Brands we work with — logo, name, and primary domain.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * Primary domain, e.g. "example.com". Protocol (http://, https://) and trailing slashes are stripped automatically.
   */
  domain: string;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Partners we collaborate with — rendered on /about.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  /**
   * Short line shown after the name, e.g. "Brand and interface craft."
   */
  tagline: string;
  /**
   * External URL the partner name links to.
   */
  href: string;
  /**
   * Font Awesome icon name (e.g. "palette", "flask", "pen-nib"). Rendered via ServiceIcon. Browse at https://fontawesome.com/icons?s=slab&m=regular
   */
  icon: string;
  /**
   * Optional. When set, rendered instead of the icon.
   */
  image?: (number | null) | Media;
  displayOrder: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Submissions from the website contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  message: string;
  /**
   * What they need help with.
   */
  help?: string | null;
  branch?: string | null;
  scope?: string | null;
  goal?: string | null;
  pain?: string | null;
  otherContext?: string | null;
  timeline?: string | null;
  budget?: string | null;
  emailStatus?: ('pending' | 'sent' | 'failed') | null;
  emailError?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People/orgs we send proposals to and work with.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  /**
   * Optional. Renders below the project name in proposal headers.
   */
  tagline?: string | null;
  defaultLogo?: (number | null) | Media;
  contacts?:
    | {
        name?: string | null;
        email?: string | null;
        phone?: string | null;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  status?: ('prospect' | 'active' | 'inactive' | 'archived') | null;
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client proposals — authored here, rendered on apps/web, exported to PDF via the browser. Use the in-form "Duplicate this proposal" button to copy — the default Duplicate action will hit the unique-slug constraint.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposals".
 */
export interface Proposal {
  id: number;
  /**
   * Admin-only label. e.g. "Consultway — Proposal A".
   */
  internalTitle: string;
  /**
   * Public URL: /proposals/<urlSlug>. Should be hard to guess.
   */
  urlSlug: string;
  client: number | Client;
  projectName: string;
  /**
   * e.g. "Website Development", "Companies & Tender Platform".
   */
  subtitle?: string | null;
  /**
   * Falls back to the client's defaultLogo if blank.
   */
  logo?: (number | null) | Media;
  accentColor?: string | null;
  fontFamily?: ('League Spartan' | 'Inter' | 'Space Mono' | 'Custom') | null;
  /**
   * Date shown in header. Defaults to today.
   */
  proposalDate: string;
  overview: string;
  /**
   * Cards in the "At a Glance" row. e.g. Timeline + Total Cost for a project, or Monthly Fee + Contract Length for maintenance.
   */
  summaryCards?:
    | {
        label: string;
        value: string;
        /**
         * Small line under the value. e.g. "+18% GST".
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  scopeItems?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Override e.g. for maintenance: "Monthly Fee".
   */
  costSectionLabel?: string | null;
  /**
   * Override e.g. "Monthly Total".
   */
  costTotalLabel?: string | null;
  /**
   * Renderer skips the cost-breakdown section when empty.
   */
  costItems?:
    | {
        item: string;
        /**
         * In rupees. Formatted as ₹X,XX,XXX in the rendered page.
         */
        amount: number;
        id?: string | null;
      }[]
    | null;
  techStack?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  recurringCosts?:
    | {
        item: string;
        /**
         * Free-form, e.g. "₹500–2,000/mo".
         */
        cost: string;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  paymentTerms?:
    | {
        milestone: string;
        sharePercent: number;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'sent' | 'accepted' | 'rejected' | 'cold' | 'withdrawn';
  /**
   * When you sent the PDF/link. Auto-set to now when status flips to "sent" — editable.
   */
  sentAt?: string | null;
  sentTo?:
    | {
        name?: string | null;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  sentMethod?: ('email' | 'whatsapp' | 'in-person' | 'other')[] | null;
  /**
   * Update on any back-and-forth. Drives the "cold" auto-flag (3 weeks of silence → cold).
   */
  lastContactAt?: string | null;
  respondedAt?: string | null;
  /**
   * Optional: archive the exact PDF you sent.
   */
  attachedPdf?: (number | null) | Media;
  /**
   * Running negotiation/follow-up notes. author + createdAt are stamped on save.
   */
  notes?:
    | {
        note: string;
        author?: (number | null) | User;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'proposals';
        value: number | Proposal;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blurb?: T;
  icon?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  flagship?: T;
  icon?: T;
  tags?: T;
  summary?: T;
  description?: T;
  prices?:
    | T
    | {
        label?: T;
        amount?: T;
        suffix?: T;
        note?: T;
        id?: T;
      };
  inclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  exclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  displayOrder?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  url?: T;
  repoUrl?: T;
  client?: T;
  cover?: T;
  tags?: T;
  description?: T;
  featured?: T;
  displayOrder?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  domain?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  href?: T;
  icon?: T;
  image?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  help?: T;
  branch?: T;
  scope?: T;
  goal?: T;
  pain?: T;
  otherContext?: T;
  timeline?: T;
  budget?: T;
  emailStatus?: T;
  emailError?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  defaultLogo?: T;
  contacts?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        role?: T;
        id?: T;
      };
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposals_select".
 */
export interface ProposalsSelect<T extends boolean = true> {
  internalTitle?: T;
  urlSlug?: T;
  client?: T;
  projectName?: T;
  subtitle?: T;
  logo?: T;
  accentColor?: T;
  fontFamily?: T;
  proposalDate?: T;
  overview?: T;
  summaryCards?:
    | T
    | {
        label?: T;
        value?: T;
        caption?: T;
        id?: T;
      };
  scopeItems?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  costSectionLabel?: T;
  costTotalLabel?: T;
  costItems?:
    | T
    | {
        item?: T;
        amount?: T;
        id?: T;
      };
  techStack?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  recurringCosts?:
    | T
    | {
        item?: T;
        cost?: T;
        notes?: T;
        id?: T;
      };
  paymentTerms?:
    | T
    | {
        milestone?: T;
        sharePercent?: T;
        id?: T;
      };
  status?: T;
  sentAt?: T;
  sentTo?:
    | T
    | {
        name?: T;
        email?: T;
        id?: T;
      };
  sentMethod?: T;
  lastContactAt?: T;
  respondedAt?: T;
  attachedPdf?: T;
  notes?:
    | T
    | {
        note?: T;
        author?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-card-settings".
 */
export interface RateCardSetting {
  id: number;
  taxNote?: string | null;
  currency?: ('INR' | 'USD') | null;
  footerDisclaimer?: string | null;
  contactCta?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Sender identity and recipient lists for outbound and form-notification emails.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-settings".
 */
export interface EmailSetting {
  id: number;
  fromName: string;
  /**
   * Must be on a domain verified in Resend. Used as the default From for forgot-password and notification emails.
   */
  fromEmail: string;
  /**
   * Emails that receive a notification when the website contact form is submitted.
   */
  contactRecipients?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-card-settings_select".
 */
export interface RateCardSettingsSelect<T extends boolean = true> {
  taxNote?: T;
  currency?: T;
  footerDisclaimer?: T;
  contactCta?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-settings_select".
 */
export interface EmailSettingsSelect<T extends boolean = true> {
  fromName?: T;
  fromEmail?: T;
  contactRecipients?:
    | T
    | {
        email?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}