export type SeedTag = { slug: string; label: string }

// Curated vocabulary. Tools/tech use TitleCase labels; content-shape tags are
// Sentence case. Slugs are lowercase-kebab; auto-generated by the Tags collection
// beforeValidate hook, but declared explicitly here so seed refs are stable.
export const allSeedTags: SeedTag[] = [
  // Tools / tech
  { slug: 'astro', label: 'Astro' },
  { slug: 'payload', label: 'Payload' },
  { slug: 'typescript', label: 'TypeScript' },
  { slug: 'tailwind', label: 'Tailwind' },
  { slug: 'figma', label: 'Figma' },
  { slug: 'cloudflare', label: 'Cloudflare' },
  { slug: 'shopify', label: 'Shopify' },

  // Content shape / form
  { slug: 'e-commerce', label: 'E-commerce' },
  { slug: 'cms', label: 'CMS' },
  { slug: 'seo', label: 'SEO' },
  { slug: 'analytics', label: 'Analytics' },
  { slug: 'performance', label: 'Performance' },
  { slug: 'email', label: 'Email' },
  { slug: 'social', label: 'Social' },
  { slug: 'print', label: 'Print' },
  { slug: 'packaging', label: 'Packaging' },
  { slug: 'branding', label: 'Branding' },
  { slug: 'ads', label: 'Ads' },
  { slug: 'maintenance', label: 'Maintenance' },
]
