// Auto-generated by scripts/fetch-project-fallbacks.mjs
// Maps project slug -> local cover path (served from /public).
// Combines CMS Payload covers (synced locally) and og:image fallbacks.

export const projectFallbacks: Record<string, string> = {
  "arcade": "/projects/fallback/arcade.jpg",
  "ascencus": "/projects/fallback/ascencus.png",
  "bombay-shirts-designer": "/projects/fallback/bombay-shirts-designer.jpg",
  "caffeinated": "/projects/fallback/caffeinated.png",
  "hot-planet": "/projects/fallback/hot-planet.png",
  "isronaut": "/projects/fallback/isronaut.png",
  "mecha-comet": "/projects/fallback/mecha-comet.png",
  "rooshad-shroff": "/projects/fallback/rooshad-shroff.jpg",
  "seed-valley": "/projects/fallback/seed-valley.png",
  "sm0l-dev": "/projects/fallback/sm0l-dev.png",
  "supervillains": "/projects/fallback/supervillains.jpg",
  "swiggy-moments": "/projects/fallback/swiggy-moments.jpg",
  "washi-sde": "/projects/fallback/washi-sde.png",
};

export const getProjectFallback = (slug: string): string | null =>
  projectFallbacks[slug] ?? null;
